### ISSUE TITLE
PlaceOrders function of NG-API library which always returns null

### ISSUE THREAD

**Issue by gmpat4u** [joelpob/betfairng#12]
Hi, I am trying to place bets using my live key and using PlaceOrders function of NG-API library which always returns null. And if I check account, the orders are not even placed.

I need help to make this working.

var res = BetfairClient.PlaceOrders(marketBook.MarketId, instructions).Result.Response;
Where "res" is always null.

Here is a screenshot of the errors:
![image](https://cloud.githubusercontent.com/assets/1518853/19297015/a709dd6c-908c-11e6-9e30-8f37b7de0112.png)

Here is my app keys status:
![image](https://cloud.githubusercontent.com/assets/1518853/19297050/e604ee6c-908c-11e6-9973-cfe310ae99f7.png)

This is how I build my PlaceInstructions:
![image](https://cloud.githubusercontent.com/assets/1518853/19297084/35f40d90-908d-11e6-8e72-80944b0ea121.png)

This is how I try to execute PlaceOrders:
![image](https://cloud.githubusercontent.com/assets/1518853/19297101/4952d6be-908d-11e6-900c-3d765d26b822.png)

Debug screens with info generated withing Order Placement Instructions:
![image](https://cloud.githubusercontent.com/assets/1518853/19297706/3201cf5a-9093-11e6-8ced-b78d291d6efb.png)

![image](https://cloud.githubusercontent.com/assets/1518853/19297710/3cfa5af8-9093-11e6-92dd-ec63dee565ca.png)

Would you please guide me what is require to place bets successfully using PlaceOrders function/api?

**Comment by joelpob** [comment]
Thanks for raising this issue. LimitOrder has a few optional parameters that weren't optional in my initial implementation. Fixed in the latest commit and your code should work now!
