### ISSUE TITLE
Syntax errors in MS Visual Studio professional 2013

### ISSUE THREAD

**Issue by SilentSwordCZ** [joelpob/betfairng#13]
Hello,
first at all i want to thank you for nice Betfair library. 

I started trying your code in C# in MS Visual Studio 2013. When i try to build solution i get upcoming errors. I do not know (because i am newbie in C#] if these errors are by some vrong setting in Visual studio or it's misspellings or something else. Thank you for advice.

1) MarketListenerPeriodic.cs
line 134 "_polling?.Dispose();"
2) MarketListenerMultiPeriod.cs
line 223 "poll.Value?.Dispose();"

In case 1) and 2) i removed char ? and syntax is fine

3) "ConsoleExample\OriginalExample.cs"
line 14 "public bool IsBlocking => false;"
line 21 "public bool IsBlocking => true;"
line 23 "public bool IsBlocking => true;"
line 29 "public bool IsBlocking => false;"

In case 3) i removed char > and syntax is fine

Is my corrections right, or i do some other mistake, which causes these errors?
Thanks in advance

**Comment by csutcliff** [comment]
VS 2013 doesn't have c# 6.0 by default. These are c# 6.0 syntax.

**Comment by SilentSwordCZ** [comment]
Thanks
