### ISSUE TITLE
Test prog does not respond

### ISSUE THREAD

**Issue by phrenetic** [joelpob/betfairng#2]
I'm sure I am doing something wrong here.

I've built the library and created a small program that logs on using the interactive route (as opposed to using the certificate). The login works fine and I get the necessary session id.

I then call TestAPI.Test() but the program then just sits there doing nothing.

I can trace the code going in to ListCurrencyRates and back out again, but then it just sits there waiting for a return in the main Test routine. Specifically it just sits at the line:

<pre>var currencyRates = client.ListCurrencyRates("GBP").Result;</pre>

I have checked that the request is actually being sent to the API and that a response is being sent back, but the response never seems to make it back to the main program.

What am I doing wrong?

**Comment by joelpob** [comment]
Fixed.
